name: terraform.yml

on:
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}

jobs:
  plan:
    name: Terraform Plan per Environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env_path:
          - envs/dev/us-east-1
          - envs/test/us-east-1
          - envs/prod/us-east-1
          - envs/prod/us-west-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.x

      - name: Terraform Init for ${{ matrix.env_path }}
        working-directory: ${{ matrix.env_path }}
        run: terraform init -backend-config="backend.hcl" -input=false

      - name: Terraform Format Check for ${{ matrix.env_path }}
        working-directory: ${{ matrix.env_path }}
        run: terraform fmt -check

      - name: Terraform Validate for ${{ matrix.env_path }}
        working-directory: ${{ matrix.env_path }}
        run: terraform validate

      - name: Terraform Plan for ${{ matrix.env_path }}
        working-directory: ${{ matrix.env_path }}
        run: terraform plan -input=false
